### ISSUE TITLE
provider crash when attempting to update an opsgenie_team

### ISSUE THREAD

**Issue by n-oden** [opsgenie/terraform-provider-opsgenie#324]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
`1.0.7`

### Affected Resource(s)
Please list the resources as a list, for example:
- opsgenie_team

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
We use a pretty complicated tf module to manage our opsgenie; I'm not sure reproducing it here would be germane -- the actual plan in question was extremely simple: we were just removing some users from some teams. 

You can see the full plan log here: https://gist.github.com/n-oden/22e36dcebf953b6bc53d8a435cec60a1

### Panic Output
https://gist.github.com/n-oden/7fb4ef1bc06616d80fef8dded61c2274

### Expected Behavior
No panic.

### Actual Behavior
Some panic.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Click "start new run" in terraform cloud console

### Important Factoids
This was running in terraform cloud.

**Comment by multani** [comment]
This is fixed in #318 , we are all waiting for an official release now.

**Comment by bateller** [comment]
Related to https://github.com/opsgenie/terraform-provider-opsgenie/issues/288

The release with binaries yesterday _finally_ resolved this issue: https://github.com/opsgenie/terraform-provider-opsgenie/releases/tag/v0.6.14

This issue should be considered resolved and closed

**Comment by faust64** [comment]
FYI: with 0.6.15, when attempting to change the opsgenie_team_id of my integrations, plan shows expected diff, apply does not error, ... then next plan still shows that same diff. provider is just unable to reconfigure any teams in my integration -- although I can taint those resources to fix it. no big deal. still: not crashing is cool, but doesn't mean it works.
